name: insitucore
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - pip
  - pip:
      - anndata
      - matplotlib
      - numpy
      - pandas
      - PySide6
      - scanpy
      - scikit-learn
      - scipy
      - seaborn
      - squidpy
      - louvain
      - scvi-tools
      - cellcharter
      - PySide6-QtWebEngine
